title: Welcome to my data science portfolio
description: Hello! I'm Nur Ezzati ðŸ¤“, an aspring analyst with a passion for turning data into actionable insights. With mathematics background and working experience as analyst and finance associate, I am motivated to apply my trasnferrable skills into my future data role.
theme: jekyll-theme-minimal
